# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: example-consul
version: 0.1.0
