[[ if .PrivateNetworkAccess ]]
# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: ops.dac.nokia.com/v1alpha1
kind: PrivateNetworkAccess
metadata:
  name: private-network-for-consul
spec:
  customerNetwork: [[ .PrivateNetworkAccess.CustomerNetwork ]]
  [[ if .PrivateNetworkAccess.ApnUUID ]]
  networks:
    - apnUUID: [[ .PrivateNetworkAccess.ApnUUID ]]
      additionalRoutes:
        [[ range .PrivateNetworkAccess.AdditionalRoutes ]]
        - [[ . ]]
        [[ end ]]
  [[ else if .PrivateNetworkAccess.Networks ]]
  networks:
  [[ range .PrivateNetworkAccess.Networks ]]
    [[ if .ApnUUID ]]
    - apnUUID: [[ .ApnUUID ]]
    [[ else if .NetworkID ]]
    - networkId: [[ .NetworkID ]]
    [[ end ]]
      additionalRoutes:
        [[ range .AdditionalRoutes ]]
        - [[ . ]]
        [[ end ]]
  [[ end ]]
  [[ end ]]
[[ end ]]
