[[ if .PrivateNetworkAccess ]]
# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: ops.dac.nokia.com/v1alpha1
kind: PrivateNetworkAccess
metadata:
  name: private-network-for-consul
spec:
  appNetwork: [[ .PrivateNetworkAccess.AppNetwork ]]
  [[ if .PrivateNetworkAccess.AppPodFixIp ]]
  appPodFixIp:
    [[ if  .PrivateNetworkAccess.AppPodFixIp.Db ]]
    statefulsets.apps/example-consul: [[ .PrivateNetworkAccess.AppPodFixIp.Db ]]
    [[ end ]]
  [[ end ]]
  [[ if .PrivateNetworkAccess.NetworkInterfaceName ]]
  networkInterfaceName: [[ .PrivateNetworkAccess.NetworkInterfaceName ]]
  [[ end ]]
  [[ if .PrivateNetworkAccess.ApnUUID ]]
  networks:
    - apnUUID: [[ .PrivateNetworkAccess.ApnUUID ]]
      [[ if .PrivateNetworkAccess.AdditionalRoutes ]]
      additionalRoutes:
        [[ range .PrivateNetworkAccess.AdditionalRoutes ]]
        - [[ . ]]
        [[ end ]]
      [[ end ]]
  [[ else if .PrivateNetworkAccess.Networks ]]
  networks:
  [[ range .PrivateNetworkAccess.Networks ]]
    [[ if .ApnUUID ]]
    - apnUUID: [[ .ApnUUID ]]
    [[ else if .NetworkID ]]
    - networkId: [[ .NetworkID ]]
    [[ end ]]
    [[ if .AdditionalRoutes ]]
      additionalRoutes:
        [[ range .AdditionalRoutes ]]
        - [[ . ]]
        [[ end ]]
    [[ end ]]
  [[ end ]]
  [[ end ]]
[[ end ]]
